b = int(input("Input number of value(s): "))
i = 0
psum = 1
old = psum
while i < b:
    if b == 1:
        n = float(input(""))
        i += 1
        print("Weighted Avg = %.4f"% n)
    elif b == 10:
        n1,n2,n3,n4,n5,n6,n7,n8,n9,n10 = input("").split()
        n1 = float(n1)
        n2 = float(n2)
        n3 = float(n3)
        n4 = float(n4)
        n5 = float(n5)
        n6 = float(n6)
        n7 = float(n7)
        n8 = float(n8)
        n9 = float(n9)
        n10 = float(n10)
        psum = n1
        old = psum
        psum = (n2+old)/2
        old = psum
        psum = (n3+old)/2
        old = psum
        psum = (n4+old)/2
        old = psum
        psum = (n5+old)/2
        old = psum
        psum = (n6+old)/2
        old = psum
        psum = (n7+old)/2
        old = psum
        psum = (n8+old)/2
        old = psum
        psum = (n9+old)/2
        old = psum
        psum = (n10+old)/2
        old = psum
        i = 10
        print("Weighted Avg = %.4f"% psum)
    else:
        n1,n2,n3,n4 = input("").split()
        n1 = float(n1)
        n2 = float(n2)
        n3 = float(n3)
        n4 = float(n4)
        psum = n1
        old = psum
        psum = (n2+old)/2
        old = psum
        psum = (n3+old)/2
        old = psum
        psum = (n4+old)/2
        old = psum
        i = 4
        print("Weighted Avg = %.4f"% psum)